// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsuXLn_CmWqGHGEfGdBovD0LytAEEH3ak',
    appId: '1:156154723251:web:d29cb23e6b0f8c7c6ca9c6',
    messagingSenderId: '156154723251',
    projectId: 'list-pedidos',
    authDomain: 'list-pedidos.firebaseapp.com',
    databaseURL: 'https://list-pedidos-default-rtdb.firebaseio.com',
    storageBucket: 'list-pedidos.firebasestorage.app',
    measurementId: 'G-3KP9HQVESD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpINi_7yXaiHjUNY720nj48sxeTnV9SW0',
    appId: '1:156154723251:android:436522770ffd12546ca9c6',
    messagingSenderId: '156154723251',
    projectId: 'list-pedidos',
    databaseURL: 'https://list-pedidos-default-rtdb.firebaseio.com',
    storageBucket: 'list-pedidos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzDVrkdRAUw-WqaAlet5xPI-riTABtX4c',
    appId: '1:156154723251:ios:9eaf7c8f638d1c696ca9c6',
    messagingSenderId: '156154723251',
    projectId: 'list-pedidos',
    databaseURL: 'https://list-pedidos-default-rtdb.firebaseio.com',
    storageBucket: 'list-pedidos.firebasestorage.app',
    iosBundleId: 'com.pedidosdp.app.pedidosdp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzDVrkdRAUw-WqaAlet5xPI-riTABtX4c',
    appId: '1:156154723251:ios:9eaf7c8f638d1c696ca9c6',
    messagingSenderId: '156154723251',
    projectId: 'list-pedidos',
    databaseURL: 'https://list-pedidos-default-rtdb.firebaseio.com',
    storageBucket: 'list-pedidos.firebasestorage.app',
    iosBundleId: 'com.pedidosdp.app.pedidosdp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsuXLn_CmWqGHGEfGdBovD0LytAEEH3ak',
    appId: '1:156154723251:web:33525b2ee69e72f66ca9c6',
    messagingSenderId: '156154723251',
    projectId: 'list-pedidos',
    authDomain: 'list-pedidos.firebaseapp.com',
    databaseURL: 'https://list-pedidos-default-rtdb.firebaseio.com',
    storageBucket: 'list-pedidos.firebasestorage.app',
    measurementId: 'G-YWGEVFZBK7',
  );
}
